server:
  port: 8080

spring:
  datasource:
    primary:
      username: root
      password: root
      url: jdbc:mysql:///student?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Hongkong
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      username: root
      password: root
      url: jdbc:mysql:///teacher?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Hongkong
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    show-sql: true
  profiles:
    include: db,ip
  debug: true

synchronize:
  SynchronUrl: http://localhost:9080

