server:
  port: 8080

spring:
  datasource:
    primary:
      username: root
      password: root
      url: jdbc:mysql:///student?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Hongkong
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      username: root
      password: root
      url: jdbc:mysql:///teacher?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Hongkong
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    show-sql: true
  profiles:
    include: db,ip
  debug: true

  #配置Redis
  redis:
    database: 0         #Redis数据库索引默认为0
    host: 127.0.0.1     #Redis服务器的IP地址
    port: 6379          #Redis服务器的连接端口号
    password: 123456    #Redis服务器的连接密码
    pool:
      max-active: 8     #连接池的最大连接数
      max-wait: -1     #连接池的最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8       #连接池中的最大空闲连接
      min-idle: 0     #连接池中的最大空闲连接
    timeout: 3000       #连接超时时间（毫秒）


synchronize:
  SynchronUrl: http://localhost:9080

